### ISSUE TITLE
About the detection categories of VG-1800

### ISSUE THREAD

**Issue by ZHUXUHAN** [waxnkw/IETrans-SGG.pytorch#10]
hi,sir, i see the object categories of your proposed VG-1800 is 70098, do you detect all the objects categories?
but i see your code using the same detector's checkpoints as Tang‘s sceng_graph_benchmark project, cao you explain it?

**Comment by waxnkw** [comment]
Yes, I use all object categories. I do not modify the detector part. Typically, in SGG models, the object classification is not done by the object detector but jointly predicted with relationships by the SGG model.  Thus, the output categories of our SGG model are 70,098. Of course, the weak feature extractor (detector part) will somewhat undermine the overall performance.

But, in this work, we mainly focus on fine-grained relationship recognition, where we pay less attention to the object feature part and leave it for future work. To make sure fairness, we also use this detector for other baseline models.

Moreover, I think a detector with 70,098 classes will be very costly. You can take a try. Maybe seeking help from open-vocabulary classifiers like CLIP will be a possible solution.

**Comment by ZHUXUHAN** [comment]
thanks for your answer~
