### ISSUE TITLE
How to generate scene graph in custom image?

### ISSUE THREAD

**Issue by Thinking-more** [waxnkw/IETrans-SGG.pytorch#2]
Hallo, could you teach me how to generate scene graph in custom image? I'm a new man in this area. Thanks!

**Comment by waxnkw** [comment]
I think the author of the SGG framework provides a way to generate scene graphs in custom images. The link is at https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch#SGDet-on-custom-images. So, are there any problems?
