### ISSUE TITLE
Environment on A100 with cuda 12.2

### ISSUE THREAD

**Issue by Edward-JianQAQ** [waxnkw/IETrans-SGG.pytorch#22]
May I ask if there is some guide on how to build an environment on A100 with CUDA 12.2 installed? I have tried for a week but still have errors when installing apex and building the package (the last two steps in the install.md). All of the errors are CUDA-related errors like: 

```shell
<command-line>: fatal error: cuda_runtime.h: No such file or directory
``` 

Btw, is this model able to run on a single 1080Ti?

I am now urgently needing your model to perform some tasks. Thank you for the help in advance!

**Comment by waxnkw** [comment]
Sorry, I do not try it on A100 with CUDA 12.2 before. Maybe you can check with https://github.com/NVIDIA/apex/issues to see whether there are some related issues. I guess it is able to run it on a single 1080Ti. Actually, I run the training on 2 2080Ti(11G). You can reduce the batch size for 1 GPU.
