### ISSUE TITLE
may you help about some puzzlement for external relabel?

### ISSUE THREAD

**Issue by Yuqifan1117** [waxnkw/IETrans-SGG.pytorch#4]
dear sir,
i want to reproduce your results with IETrans methods. However, in external stage, i first met a problem with different length of 'img_info' and 'specified_data', then i filter the 'img_info', only keeping the same image in 'specified_data_file'. But in training stage, there is a bug about `'RuntimeError: CUDA error: device-side assert triggered' '/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [124,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.'`  I think it may be caused by wrong split for train/val/test set, therefore, may i know how you split the dataset for train/val/test and how you get the specified_data_file?

**Comment by waxnkw** [comment]
Can you show me the script you used for the external transfer?

**Comment by Yuqifan1117** [comment]
ok, i will try this as you say. By the way, I used the script `cmds/50/transformer/predcls/lt/external/relabel.sh` for the external transfer.

**Comment by waxnkw** [comment]
I update `cmds/50/transformer/predcls/lt/external/relabel.sh` last week and fix a bug today. If you clone the repo previously, you can also update the repo.

**Comment by Yuqifan1117** [comment]
thanks a lot! If I used the original split according to what you provided, there may be no problem. By the way, may I know your pre-setting of validation set is just split the first 5000 images or has another precessing?

**Comment by waxnkw** [comment]
Actually, I forget how I set the 5000 images. I guess I just run [Scene-Graph-Benchmark.pytorch](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch)'s dataset code and choose images that they split as validation.
