### ISSUE TITLE
Download visual genome dataset

### ISSUE THREAD

**Issue by dneirfi** [waxnkw/IETrans-SGG.pytorch#7]
Hi. Thank you for sharing the nice work!

When I try to download visual genome dataset, I got "You don't have permission to access /people/rak248/VG_100K_2/images.zip on this server." error. 

How can I fix it?

Thanks.

**Comment by waxnkw** [comment]
It seems like something wrong with the Visual Genome dataset's official link. I also take a try from their official website and meet the problem with you. I will try to upload the images from my own computer later.

**Comment by dneirfi** [comment]
Thanks for reply!

**Comment by waxnkw** [comment]
Please try these two links for [images.zip](https://thunlp.oss-cn-qingdao.aliyuncs.com/images.zip) and [images2.zip](https://thunlp.oss-cn-qingdao.aliyuncs.com/images2.zip).
